#
# Copyright (c) 2021 Wasiq Bhamla.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
description: >
  Compile and build the Maven project.
parameters:
  command:
    type: string
    default: mvn install -DskipTests
    description: Maven Build command to execute.
  attach:
    type: boolean
    description: Attach the workspace.
    default: true
  persist:
    type: boolean
    description: Persist command to workspace.
    default: true
  mentions:
    type: string
    description: Comma separated list of Discord User ID, without spaces.
    default: ${DISCORD_MENTIONS}
  fail_only:
    type: boolean
    default: true
    description: Notify only for Failed job.
steps:
  - attach-workspace:
      attach: << parameters.attach >>
  - run:
      name: Build project
      command: << parameters.command >>
  - persist-workspace:
      persist: << parameters.persist >>
  - notify:
      mentions: << parameters.mentions >>
      fail_only: << parameters.fail_only >>
