# How to author commands: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands
description: >
  Configure GPG private keys.
steps:
  - run:
      name: Configure GPG private key for signing project artifacts in OSS Sonatype
      command: << include(scripts/configure-gpg.sh) >>
