# How to author commands: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands
description: >
  Configure Git to allow pushing the version change and tags back to GitHub.
steps:
  - create-gpg-exec-script
  - configure-ssh-key
  - run:
      name: Configure GIT with host fingerprint, user info and SSH key for pushing
      command: <<include(scripts/configure-git.sh)>>
