description: >
  Compile and build the Maven project.
parameters:
  executor-version:
    type: string
    default: 11-jdk-stretch
    description: Default executor image version.
  command:
    type: string
    default: mvn install -DskipTests
    description: Maven Build command to execute.
  attach:
    type: boolean
    description: Attach the workspace.
    default: true
  persist:
    type: boolean
    description: Persist command to workspace.
    default: true
  mentions:
    type: string
    description: Comma separated list of Slack User ID, without spaces.
    default: ${SLACK_MENTIONS}
  fail_only:
    type: boolean
    default: true
    description: Notify only for Failed job.
executor:
  name: maven
  tag: << parameters.executor-version >>
steps:
  - build:
      command: << parameters.command >>
      attach: << parameters.attach >>
      persist: << parameters.persist >>
      mentions: << parameters.mentions >>
      fail_only: << parameters.fail_only >>
